version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=node_ts_crud
    volumes:
      - node_ts_crud_data:/postgresql/data

volumes:
  node_ts_crud_data:
